### PR TITLE
Updated the README.md file.

### PR DESCRIPTION
**Pull request by SiddAjmera**
Replaced `entries` with `zip.entries()`

### CODE REVIEW

**Comment by antelle** [comment]
🎁  thanks!

**Comment by SiddAjmera** [comment]
@antelle , I'm getting an error while extracting all the contents of a zip. Apparently it's not making subfolders from a level. Can you please help?

**Comment by antelle** [comment]
Could you please elaborate more? I don't understand what you mean.

**Comment by SiddAjmera** [comment]
I'm getting errors like `Error: ENOENT: no such file or directory, mkdir` when I'm trying to run

`zip.extract(null, './extracted', (err, count) => {
      console.log(err ? `Extract error: ${err}` : `Extracted ${count} entries`);

      zip.on('extract', (entry, file) => {
        console.log(`Extracted ${entry.name} to ${file}`);
      });

      zip.close();
    });`

**Comment by antelle** [comment]
Do you have `./extracted` directory in FS? It must exist.

**Comment by SiddAjmera** [comment]
Yes I have one. I'm also getting folders generated inside when I call extract. But there isn't any file inside them. All the generated folders are empty.

**Comment by antelle** [comment]
Is it possible to upload a zip file? Maybe there's something special about it?

**Comment by SiddAjmera** [comment]
Sure. I'll upload the zip. Here's the SS of the extracted folder.

image

**Comment by SiddAjmera** [comment]
@antelle , any updates?

**Pull request merged**
